<a href="https://colab.research.google.com/github/TheBull8/MachineLearning/blob/main/Notebooks/NeuralNetworkCanopy3Features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Using Canopy Radius, we first determine the DBH as a test. We will then add additional features: age, species, and Lat/Lon.
Tensorflow and Keras libraries.

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd
from datetime import datetime
from datetime import datetime, timedelta

#Select either YellowN or OrangeN csv file
df = pd.read_csv('YellowOrangeN.csv')

In [2]:
#Age Column computing
def convert_to_date(date_string):
    return datetime.strptime(date_string, '%b-%y').date()

df['DP2'] = df['datePlanted'].apply(convert_to_date)
D1 = datetime.now() - timedelta(days=200)
df['Age'] = (D1 - pd.to_datetime( df['datePlanted'].apply(convert_to_date))).dt.days


In [3]:
# Define a mapping dictionary
mapping = {'Mangifera indica': 1, 'Persea americana': 2}

# Create the new column by mapping the values
df['speciesCode'] = df['species'].map(mapping)

In [8]:
x = df[['canopy', 'Age', 'speciesCode']].to_numpy().reshape((-1, 3))
y = np.array(df['DBH'].to_numpy())


[[2.000e-02 5.770e+02 1.000e+00]
 [2.000e-02 3.930e+02 2.000e+00]
 [3.000e-02 5.770e+02 1.000e+00]
 ...
 [1.550e+00 1.854e+03 1.000e+00]
 [2.300e+00 1.854e+03 2.000e+00]
 [2.300e+00 1.854e+03 2.000e+00]]


In [7]:
np.random.seed(0)
X_train = np.random.rand(100, 3)  # 100 samples with 3 input features



[[2.000e-02 5.770e+02 1.000e+00]
 [2.000e-02 3.930e+02 2.000e+00]
 [3.000e-02 5.770e+02 1.000e+00]
 ...
 [1.550e+00 1.854e+03 1.000e+00]
 [2.300e+00 1.854e+03 2.000e+00]
 [2.300e+00 1.854e+03 2.000e+00]]


In [10]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Generate some synthetic data for training
np.random.seed(0)
#X_train = np.random.rand(100, 3)  # 100 samples with 3 input features
#y_train = 2 * X_train[:, 0] + 3 * X_train[:, 1] - 1 * X_train[:, 2] + np.random.randn(100)

# Build the neural network model
model = keras.Sequential([
    layers.Dense(16, activation='relu', input_shape=(3,)),
    layers.Dense(8, activation='relu'),
    layers.Dense(1)  # Output layer with 1 neuron (for regression)
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(x, y, epochs=100, verbose=1)

# Now you can use the trained model for predictions
# Example prediction for a new input
new_input = np.array([[0.3, 577, 1]])
predicted_output = model.predict(new_input)
print("Predicted Output:", predicted_output)


Epoch 1/100
14/14 [==============================] - 1s 3ms/step - loss: 39893.5820
Epoch 2/100
14/14 [==============================] - 0s 3ms/step - loss: 14777.5039
Epoch 3/100
14/14 [==============================] - 0s 2ms/step - loss: 3198.5898
Epoch 4/100
14/14 [==============================] - 0s 2ms/step - loss: 334.1774
Epoch 5/100
14/14 [==============================] - 0s 2ms/step - loss: 13.0468
Epoch 6/100
14/14 [==============================] - 0s 2ms/step - loss: 33.2354
Epoch 7/100
14/14 [==============================] - 0s 3ms/step - loss: 9.5639
Epoch 8/100
14/14 [==============================] - 0s 2ms/step - loss: 0.3971
Epoch 9/100
14/14 [==============================] - 0s 2ms/step - loss: 0.3694
Epoch 10/100
14/14 [==============================] - 0s 2ms/step - loss: 0.1818
Epoch 11/100
14/14 [==============================] - 0s 2ms/step - loss: 0.0597
Epoch 12/100
14/14 [==============================] - 0s 3ms/step - loss: 0.0620
Epoch 13/100
14/14 [==

# THIS IS THE SAMPLE CODE FROM CHATGPT. It is NOT needed for us, just a sanity check test.
import numpy as np
import tensorflow as tf
from tensorflow import keras

# Generate some sample data
# Here, we have one input feature (X) and one output (y).
X = np.array([1.0, 2.0, 3.0, 4.0, 5.0])  # Input feature
y = np.array([2.0, 4.0, 6.0, 8.0, 10.0])  # Corresponding output

# Define a simple neural network model
model = keras.Sequential([
    keras.layers.Dense(units=1, input_shape=[1])  # One input feature, one output unit
])

# Compile the model
model.compile(optimizer='sgd', learning_rate = 0.001, loss='mean_squared_error', metrics=['accuracy'])

# Train the model
model.fit(X, y, epochs=100)  # You can adjust the number of epochs as needed

# Make predictions
predictions = model.predict([6.0, 7.0])  # Predict the output for new inputs

print(predictions)
